name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # Setup Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: composeApp/build/outputs/apk/debug/androidApp-debug.apk
